version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - .:/var/www/baby_app
    working_dir: /var/www/baby_app
    # command: ./bin/docker-entrypoint ./bin/rails server -b '0.0.0.0'
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
     timeout: 20s
     retries: 10