version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - .:/var/www/baby_app
    working_dir: /var/www/baby_app
    command: ./bin/docker-entrypoint
    ports:
      - "3000:3000"
    tty: true